import { useMemo } from "react";
import { createStore } from "zustand";
import type { GalleryColumn, TagDef, TagFilterMode } from "../lib/types";
import { cmd } from "../lib/tauri";
import { invalidateImageMetadata } from "../lib/metadataCache";
import { imageIndexOf, taggedImageIndexOf, useSessionStore } from "./sessionStore";
import { tabScoped } from "./tabScoped";
import type { TabStores } from "./tabStores";

type State = {
  /** The open project's vocabulary, in display order (project.json tagDefs). */
  defs: TagDef[];
  /** Lowercased tag name -> color, derived from `defs` and kept in lockstep
   *  with it. Exists because every Thumbnail resolves a color for every tag it
   *  carries: with a linear scan of `defs` that was tags×defs string compares
   *  per gallery render, which at a few hundred thumbnails is thousands of
   *  comparisons for data that changes only when the vocabulary does.
   *
   *  Held as state rather than derived in a selector on purpose — a zustand
   *  selector returning a freshly-built Map would never be referentially equal
   *  and would re-render every subscriber on every store touch. */
  colorsByName: Map<string, string>;
  /** Tag names currently narrowing the gallery. Empty = no filtering. */
  activeFilter: string[];
  filterMode: TagFilterMode;
  /** `generatedBy` value narrowing the gallery, ANDed with `activeFilter`.
   *  At most one — an image has exactly one generatedBy, so unlike tags this
   *  is a single value rather than a list. */
  activeUserFilter: string | null;
};

type Actions = {
  loadDefs: (projectPath: string | null) => Promise<void>;
  setImageTags: (path: string, tags: string[]) => Promise<void>;
  toggleImageTag: (path: string, tag: string) => Promise<void>;
  renameTag: (oldName: string, newName: string) => Promise<void>;
  deleteTag: (name: string) => Promise<void>;
  setDefs: (defs: TagDef[]) => Promise<void>;
  setColor: (name: string, color: string) => Promise<void>;
  toggleFilter: (tag: string) => void;
  setFilterMode: (mode: TagFilterMode) => void;
  /** Toggles a "generated by" filter: clicking the already-active user
   *  clears it, clicking another swaps to it. */
  setUserFilter: (name: string) => void;
  clearFilter: () => void;
};

/** Case-insensitive tag comparison — the single definition. Deliberately
 *  `toLowerCase`, never `toLocaleLowerCase`: the Rust side does its own
 *  comparison (`eq_ignore_ascii_case`), and a locale-sensitive fold here
 *  (Turkish dotted/dotless I being the classic trap) would make the two ends
 *  disagree about which tags are the same tag. */
export const tagsEqual = (a: string, b: string) =>
  a.toLowerCase() === b.toLowerCase();

const eq = tagsEqual;

/** Fallback color for a tag an image carries that the vocabulary hasn't
 *  caught up with (a sidecar edited outside the app, say). */
export const UNKNOWN_TAG_COLOR = "var(--color-dim)";

/** First-wins, matching the `defs.find(...)` this replaced. A last-wins loop
 *  would silently change the rendered color whenever a project holds two defs
 *  differing only by case. */
function colorMapOf(defs: TagDef[]): Map<string, string> {
  const m = new Map<string, string>();
  for (const d of defs) {
    const k = d.name.toLowerCase();
    if (!m.has(k)) m.set(k, d.color || UNKNOWN_TAG_COLOR);
  }
  return m;
}

/** `defs` and its derived color map, always set together. */
function defsPatch(defs: TagDef[]): Pick<State, "defs" | "colorsByName"> {
  return { defs, colorsByName: colorMapOf(defs) };
}

/** Color for a tag, given a `defs` array. Prefer subscribing to
 *  `colorsByName` in components that render many tags. */
export function tagColor(defs: TagDef[], name: string): string {
  return defs.find((d) => eq(d.name, name))?.color || UNKNOWN_TAG_COLOR;
}

/** The vocabulary as the UI should offer it: the project's `tagDefs`, plus
 *  any tag actually carried by a loaded image that they don't know about.
 *
 *  The sidecars are the source of truth for tag *names* — `tagDefs` only adds
 *  a color — so the picker and filter bar must not go blank just because
 *  project.json has drifted (a project nested under another project's
 *  `project.json` used to send every write to the outer one). Discovered tags
 *  render in the fallback color until the vocabulary is repaired. */
let discoveredCache: {
  columns: unknown;
  taggedGroups: unknown;
  names: string[];
} | null = null;

/** Distinct tag names carried by loaded images across both views, first
 *  spelling wins. Cached on the two array identities: this walks every image
 *  in the project's loaded views, and it has two callers (the filter bar and
 *  the tag editor) that would otherwise each pay for it. */
function discoveredTagNames(
  columns: { images: { tags?: string[] }[] }[],
  taggedGroups: { shots: { images: { tags?: string[] }[] }[] }[],
): string[] {
  if (
    discoveredCache &&
    discoveredCache.columns === columns &&
    discoveredCache.taggedGroups === taggedGroups
  ) {
    return discoveredCache.names;
  }
  const seen = new Map<string, string>();
  const add = (t: string) => {
    const k = t.toLowerCase();
    if (!seen.has(k)) seen.set(k, t);
  };
  for (const c of columns) for (const i of c.images) (i.tags ?? []).forEach(add);
  for (const s of taggedGroups)
    for (const sh of s.shots)
      for (const i of sh.images) (i.tags ?? []).forEach(add);

  const names = [...seen.values()];
  discoveredCache = { columns, taggedGroups, names };
  return names;
}

let effectiveCache: { key: string; result: TagDef[] } | null = null;

export function useEffectiveTagDefs(): TagDef[] {
  const defs = useTagsStore((s) => s.defs);
  const columns = useSessionStore((s) => s.columns);
  const taggedGroups = useSessionStore((s) => s.taggedGroups);
  return useMemo(() => {
    const byKey = new Map<string, TagDef>();
    for (const d of defs) byKey.set(d.name.toLowerCase(), d);
    for (const t of discoveredTagNames(columns, taggedGroups)) {
      const k = t.toLowerCase();
      if (!byKey.has(k)) byKey.set(k, { name: t, color: UNKNOWN_TAG_COLOR });
    }
    const result = [...byKey.values()];

    // `columns` gets a fresh identity after every rescan — i.e. after every
    // generation iteration — so without this the filter bar re-rendered its
    // whole chip row constantly for an unchanged vocabulary. Hand back the
    // previous array when nothing tag-relevant actually moved.
    const key = result.map((d) => `${d.name}\u0000${d.color}`).join("\u0001");
    if (effectiveCache && effectiveCache.key === key) return effectiveCache.result;
    effectiveCache = { key, result };
    return result;
  }, [defs, columns, taggedGroups]);
}

/** Distinct `generatedBy` values across both loaded views, first spelling
 *  wins — same shape and same cache-on-array-identity trick as
 *  `discoveredTagNames`, since it walks the same images on the same rescans. */
let discoveredUsersCache: {
  columns: unknown;
  taggedGroups: unknown;
  names: string[];
} | null = null;

function discoveredUserNames(
  columns: { images: { generatedBy?: string }[] }[],
  taggedGroups: { shots: { images: { generatedBy?: string }[] }[] }[],
): string[] {
  if (
    discoveredUsersCache &&
    discoveredUsersCache.columns === columns &&
    discoveredUsersCache.taggedGroups === taggedGroups
  ) {
    return discoveredUsersCache.names;
  }
  const seen = new Map<string, string>();
  const add = (u: string | undefined) => {
    if (!u) return;
    const k = u.toLowerCase();
    if (!seen.has(k)) seen.set(k, u);
  };
  for (const c of columns) for (const i of c.images) add(i.generatedBy);
  for (const s of taggedGroups)
    for (const sh of s.shots) for (const i of sh.images) add(i.generatedBy);

  const names = [...seen.values()].sort((a, b) => a.localeCompare(b));
  discoveredUsersCache = { columns, taggedGroups, names };
  return names;
}

export function useDiscoveredUsers(): string[] {
  const columns = useSessionStore((s) => s.columns);
  const taggedGroups = useSessionStore((s) => s.taggedGroups);
  return useMemo(
    () => discoveredUserNames(columns, taggedGroups),
    [columns, taggedGroups],
  );
}

/** Does an image satisfy the active filter — its tags against `filter`
 *  (ANY/ALL per `mode`), ANDed with `userFilter` against `generatedBy` if one
 *  is active. */
export function matchesFilter(
  tags: string[] | undefined,
  filter: string[],
  mode: TagFilterMode,
  generatedBy?: string,
  userFilter?: string | null,
): boolean {
  if (userFilter && !(generatedBy && eq(generatedBy, userFilter))) return false;
  if (filter.length === 0) return true;
  const has = (w: string) => (tags ?? []).some((t) => eq(t, w));
  return mode === "all" ? filter.every(has) : filter.some(has);
}

export type TagsState = State & Actions;

/** Per-tab: `defs` is the *open project's* vocabulary, and two tabs can hold
 *  two different projects. The filter is per-tab for the same reason — it
 *  narrows that tab's gallery. */
export function createTagsStore(tab: TabStores) {
  const session = () => tab.session.getState();

  /** Patch one image's tags into the loaded columns in place. Beats a full
   *  rescanShot (a whole-directory disk walk) for what is a one-field edit —
   *  and keeps the thumbnail from flickering on every tag click. */
  const patchColumns = (path: string, tags: string[]): void => {
    let hit = false;
    const columns: GalleryColumn[] = session().columns.map((col) => {
      if (!col.images.some((i) => i.path === path)) return col;
      hit = true;
      return {
        ...col,
        images: col.images.map((i) => (i.path === path ? { ...i, tags } : i)),
      };
    });
    if (hit) tab.session.setState({ columns } as never);
  };

  /** The tag view is server-filtered, so a filter change has to re-query it.
   *  The columns view filters client-side and needs nothing. */
  const afterFilterChange = async (): Promise<void> => {
    const s = session();
    if (s.viewMode === "tagged") await s.rescanTagged();
  };

  /** A vocabulary-wide edit rewrites sidecars across the project — reload
   *  whichever views are showing. */
  const refreshViews = async (): Promise<void> => {
    const s = session();
    if (s.shotPath) await s.rescanShot();
    if (s.viewMode === "tagged") await s.rescanTagged();
  };

  /** This tab's loaded views, for reading an image's current tags without a
   *  disk round-trip. The module-level `findLoadedImage` looks at whichever
   *  tab is in front, which is the wrong answer for a background write. */
  const findLoaded = (path: string) => {
    const s = session();
    return imageIndexOf(s.columns).get(path) ??
      taggedImageIndexOf(s.taggedGroups).get(path);
  };

  return createStore<TagsState>()((set, get) => ({
  defs: [],
  colorsByName: new Map(),
  activeFilter: [],
  filterMode: "any",
  activeUserFilter: null,

  async loadDefs(projectPath) {
    if (!projectPath) {
      set({ ...defsPatch([]), activeFilter: [] });
      return;
    }
    try {
      set(defsPatch(await cmd.project_tag_defs_get(projectPath)));
    } catch {
      set(defsPatch([]));
    }
    // Drop filter entries the new project doesn't know about.
    const names = get().defs;
    set((s) => ({
      activeFilter: s.activeFilter.filter((t) =>
        names.some((d) => eq(d.name, t)),
      ),
    }));
  },

  async setImageTags(path, tags) {
    const applied = await cmd.image_tags_set(path, tags);
    // Tags live in the sidecar now, so anything holding a cached copy of it
    // (hover tooltip, cost totals) has to re-read.
    invalidateImageMetadata(path);
    patchColumns(path, applied);
    const { projectPath, viewMode, rescanTagged } = session();
    // A new tag may have been minted server-side — pull the vocabulary back.
    await get().loadDefs(projectPath);
    if (viewMode === "tagged") void rescanTagged();
  },

  async toggleImageTag(path, tag) {
    const current =
      findLoaded(path)?.tags ??
      // Not in any loaded view (zoom modal on an image from elsewhere) —
      // read the sidecar rather than guessing "untagged" and wiping it.
      (await cmd.image_metadata_read(path).catch(() => null))?.tags ??
      [];
    const next = current.some((t) => eq(t, tag))
      ? current.filter((t) => !eq(t, tag))
      : [...current, tag];
    await get().setImageTags(path, next);
  },

  async renameTag(oldName, newName) {
    const { projectPath } = session();
    if (!projectPath) return;
    set(defsPatch(await cmd.project_tag_rename(projectPath, oldName, newName)));
    set((s) => ({
      activeFilter: s.activeFilter.map((t) => (eq(t, oldName) ? newName : t)),
    }));
    await refreshViews();
  },

  async deleteTag(name) {
    const { projectPath } = session();
    if (!projectPath) return;
    set(defsPatch(await cmd.project_tag_delete(projectPath, name)));
    set((s) => ({ activeFilter: s.activeFilter.filter((t) => !eq(t, name)) }));
    await refreshViews();
  },

  async setDefs(defs) {
    const { projectPath } = session();
    if (!projectPath) return;
    set(defsPatch(defs));
    set(defsPatch(await cmd.project_tag_defs_set(projectPath, defs)));
  },

  async setColor(name, color) {
    await get().setDefs(
      get().defs.map((d) => (eq(d.name, name) ? { ...d, color } : d)),
    );
  },

  toggleFilter(tag) {
    set((s) => ({
      activeFilter: s.activeFilter.some((t) => eq(t, tag))
        ? s.activeFilter.filter((t) => !eq(t, tag))
        : [...s.activeFilter, tag],
    }));
    void afterFilterChange();
  },

  setFilterMode(mode) {
    set({ filterMode: mode });
    void afterFilterChange();
  },

  // No afterFilterChange() here: unlike tags, the user filter narrows
  // taggedGroups client-side (TagView) rather than driving the server
  // query, so there's nothing to re-fetch.
  setUserFilter(name) {
    set((s) => ({
      activeUserFilter: s.activeUserFilter && eq(s.activeUserFilter, name) ? null : name,
    }));
  },

  clearFilter() {
    set({ activeFilter: [] });
    void afterFilterChange();
  },
  }));
}

export const useTagsStore = tabScoped((t) => t.tags);
