import type { ButtonHTMLAttributes, CSSProperties } from "react";
import { readableOn } from "../lib/colors";

type Props = ButtonHTMLAttributes<HTMLButtonElement> & {
  /** The tag's own colour. Fills the chip when `active`, and shows as a dot
   *  when not. Omit for chips that aren't tags (the "generated by" user
   *  filters), which fall back to the accent. */
  color?: string;
  active?: boolean;
};

/**
 * A tag chip. Capsule, like every other control.
 *
 * When on, the chip fills with the tag's *own* colour rather than the accent —
 * the vocabulary stays readable at a glance across a bar of active filters,
 * which a row of identical accent pills would lose. The colour dot is dropped
 * in that state because the fill already carries it.
 *
 * `color` can be the literal string "var(--color-dim)" (tagsStore's
 * UNKNOWN_TAG_COLOR, for a tag no def knows about). That works as a CSS value
 * but can't be parsed for contrast, so `readableOn` returns null and the
 * foreground falls through to the inherited text colour.
 */
export function Chip({
  color,
  active = false,
  className = "",
  type = "button",
  children,
  ...rest
}: Props) {
  const fill = color ?? "var(--color-accent)";
  const style: CSSProperties | undefined = active
    ? {
        background: fill,
        borderColor: fill,
        color: color
          ? (readableOn(color) ?? undefined)
          : "var(--color-on-accent)",
      }
    : undefined;

  return (
    <button
      type={type}
      aria-pressed={active}
      style={style}
      className={`inline-flex items-center gap-1 rounded-full border px-2 py-[1px] text-xs whitespace-nowrap cursor-pointer transition-colors ${
        active ? "" : "bg-transparent border-dim text-text hover:border-accent"
      } ${className}`}
      {...rest}
    >
      {!active && color && (
        <span
          className="w-[6px] h-[6px] rounded-full shrink-0"
          style={{ background: color }}
        />
      )}
      {children}
    </button>
  );
}
