import { useMemo } from "react";
import {
  tagsEqual,
  useDiscoveredModelIds,
  useDiscoveredUsers,
  useEffectiveTagDefs,
  useTagsStore,
} from "../stores/tagsStore";
import { Btn } from "./Btn";
import { Chip } from "./Chip";
import { ToggleGroup } from "./ToggleGroup";
import { Icon } from "../lib/icon";
import { useModelLabels } from "../lib/modelLabels";
import type { TagFilterMode } from "../lib/types";

const MODES: { value: TagFilterMode; label: string }[] = [
  { value: "any", label: "ANY" },
  { value: "all", label: "ALL" },
];

/** Chip bar above the gallery: three groups on one wrapping line — the
 *  "generated by" users, then the models, then the tags. The tag group narrows
 *  the columns view client-side and drives the project-wide tag view's query —
 *  one filter, both surfaces. The user and model groups narrow client-side on
 *  both surfaces (see galleryFilter.ts) and never touch that query.
 *
 *  The user group is single-select; the model group accumulates and reads as
 *  OR, so two models can be compared side by side. It has no ANY/ALL toggle
 *  because an image has exactly one model — ALL of two would always be empty.
 *  Neither is a sidecar tag: they read `GalleryImage.generatedBy` /
 *  `GalleryImage.modelId`, resolved at scan time the same way as `tags`. Model
 *  chips carry the *id* and render the registry's current label, so a model
 *  since renamed reads with its new name.
 *
 *  Two levels of wrapping: the outer row wraps first, so a long tag group
 *  drops whole onto its own line; only once a group has the full width to
 *  itself does it wrap internally. */
export function TagFilterBar() {
  const defs = useEffectiveTagDefs();
  const users = useDiscoveredUsers();
  const modelIds = useDiscoveredModelIds();
  const modelLabel = useModelLabels();
  const activeFilter = useTagsStore((s) => s.activeFilter);
  const filterMode = useTagsStore((s) => s.filterMode);
  const activeUserFilter = useTagsStore((s) => s.activeUserFilter);
  const activeModelFilter = useTagsStore((s) => s.activeModelFilter);
  const toggleFilter = useTagsStore((s) => s.toggleFilter);
  const setFilterMode = useTagsStore((s) => s.setFilterMode);
  const setUserFilter = useTagsStore((s) => s.setUserFilter);
  const toggleModelFilter = useTagsStore((s) => s.toggleModelFilter);
  const clearModelFilter = useTagsStore((s) => s.clearModelFilter);
  const clearFilter = useTagsStore((s) => s.clearFilter);

  // Sorted here rather than in the store: the store deals in ids (which is
  // what the filter matches on), and chip order has to follow the label the
  // user actually reads — "FLUX.1 [dev]", not "flux_dev_txt2img".
  const models = useMemo(
    () =>
      modelIds
        .map((id) => ({ id, label: modelLabel(id) }))
        .sort((a, b) => a.label.localeCompare(b.label)),
    [modelIds, modelLabel],
  );

  if (defs.length === 0 && users.length === 0 && models.length === 0)
    return null;
  const isOn = (name: string) => activeFilter.some((t) => tagsEqual(t, name));

  return (
    <div className="flex flex-wrap items-start gap-x-3 gap-y-1 shrink-0 px-2 py-1 bg-surface border-b border-border">
      {users.length > 0 && (
        <div className="flex items-center gap-1 flex-wrap">
          <Icon name="person" size={14} className="text-dim shrink-0" />
          {users.map((u) => {
            const on = activeUserFilter != null && tagsEqual(activeUserFilter, u);
            return (
              <Chip
                key={u}
                active={on}
                onClick={() => setUserFilter(u)}
                title={
                  on ? `Stop filtering by user "${u}"` : `Filter by user "${u}"`
                }
              >
                {u}
              </Chip>
            );
          })}
        </div>
      )}
      {/* Rendered while a filter is active even if no loaded image carries
          that model any more, so CLEAR stays reachable rather than stranding
          an empty gallery with nothing to click. */}
      {(models.length > 0 || activeModelFilter.length > 0) && (
        <div className="flex items-center gap-1 flex-wrap">
          <Icon name="memory" size={14} className="text-dim shrink-0" />
          {models.map((m) => {
            const on = activeModelFilter.includes(m.id);
            return (
              <Chip
                key={m.id}
                active={on}
                onClick={() => toggleModelFilter(m.id)}
                title={
                  on
                    ? `Stop filtering by model "${m.label}"`
                    : `Filter by model "${m.label}"`
                }
              >
                {m.label}
              </Chip>
            );
          })}
          {activeModelFilter.length > 0 && (
            <Btn
              onClick={clearModelFilter}
              title="Clear model filter"
              className="shrink-0"
            >
              CLEAR
            </Btn>
          )}
        </div>
      )}
      {defs.length > 0 && (
        <div className="flex items-center gap-1 flex-wrap">
          <Icon name="sell" size={14} className="text-dim shrink-0" />
          {defs.map((d) => {
            const on = isOn(d.name);
            return (
              <Chip
                key={d.name}
                color={d.color}
                active={on}
                onClick={() => toggleFilter(d.name)}
                title={
                  on ? `Stop filtering by "${d.name}"` : `Filter by "${d.name}"`
                }
              >
                {d.name}
              </Chip>
            );
          })}
          {activeFilter.length > 1 && (
            <ToggleGroup
              value={filterMode}
              options={MODES}
              onChange={setFilterMode}
              className="shrink-0"
            />
          )}
          {activeFilter.length > 0 && (
            <Btn
              onClick={clearFilter}
              title="Clear tag filter"
              className="shrink-0"
            >
              CLEAR
            </Btn>
          )}
        </div>
      )}
    </div>
  );
}
