import {
  tagsEqual,
  useDiscoveredUsers,
  useEffectiveTagDefs,
  useTagsStore,
} from "../stores/tagsStore";
import { Btn } from "./Btn";
import { Chip } from "./Chip";
import { ToggleGroup } from "./ToggleGroup";
import { Icon } from "../lib/icon";
import type { TagFilterMode } from "../lib/types";

const MODES: { value: TagFilterMode; label: string }[] = [
  { value: "any", label: "ANY" },
  { value: "all", label: "ALL" },
];

/** Chip bar above the gallery: the "generated by" user group first, then the
 *  tag group, both on one wrapping line. The tag group narrows the columns
 *  view client-side and drives the project-wide tag view's query — one filter,
 *  both surfaces. The user group is a single-select "generated by" narrowing,
 *  applied client-side on both surfaces (see Gallery.tsx and TagView.tsx).
 *
 *  Two levels of wrapping: the outer row wraps first, so a long tag group
 *  drops whole onto its own line; only once a group has the full width to
 *  itself does it wrap internally. */
export function TagFilterBar() {
  const defs = useEffectiveTagDefs();
  const users = useDiscoveredUsers();
  const activeFilter = useTagsStore((s) => s.activeFilter);
  const filterMode = useTagsStore((s) => s.filterMode);
  const activeUserFilter = useTagsStore((s) => s.activeUserFilter);
  const toggleFilter = useTagsStore((s) => s.toggleFilter);
  const setFilterMode = useTagsStore((s) => s.setFilterMode);
  const setUserFilter = useTagsStore((s) => s.setUserFilter);
  const clearFilter = useTagsStore((s) => s.clearFilter);

  if (defs.length === 0 && users.length === 0) return null;
  const isOn = (name: string) => activeFilter.some((t) => tagsEqual(t, name));

  return (
    <div className="flex flex-wrap items-start gap-x-3 gap-y-1 shrink-0 px-2 py-1 bg-surface border-b border-border">
      {users.length > 0 && (
        <div className="flex items-center gap-1 flex-wrap">
          <Icon name="person" size={14} className="text-dim shrink-0" />
          {users.map((u) => {
            const on = activeUserFilter != null && tagsEqual(activeUserFilter, u);
            return (
              <Chip
                key={u}
                active={on}
                onClick={() => setUserFilter(u)}
                title={
                  on ? `Stop filtering by user "${u}"` : `Filter by user "${u}"`
                }
              >
                {u}
              </Chip>
            );
          })}
        </div>
      )}
      {defs.length > 0 && (
        <div className="flex items-center gap-1 flex-wrap">
          <Icon name="sell" size={14} className="text-dim shrink-0" />
          {defs.map((d) => {
            const on = isOn(d.name);
            return (
              <Chip
                key={d.name}
                color={d.color}
                active={on}
                onClick={() => toggleFilter(d.name)}
                title={
                  on ? `Stop filtering by "${d.name}"` : `Filter by "${d.name}"`
                }
              >
                {d.name}
              </Chip>
            );
          })}
          {activeFilter.length > 1 && (
            <ToggleGroup
              value={filterMode}
              options={MODES}
              onChange={setFilterMode}
              className="shrink-0"
            />
          )}
          {activeFilter.length > 0 && (
            <Btn
              onClick={clearFilter}
              title="Clear tag filter"
              className="shrink-0"
            >
              CLEAR
            </Btn>
          )}
        </div>
      )}
    </div>
  );
}
