import {
  tagsEqual,
  useDiscoveredUsers,
  useEffectiveTagDefs,
  useTagsStore,
} from "../stores/tagsStore";
import { ToggleGroup } from "./ToggleGroup";
import { Icon } from "../lib/icon";
import type { TagFilterMode } from "../lib/types";

const MODES: { value: TagFilterMode; label: string }[] = [
  { value: "any", label: "ANY" },
  { value: "all", label: "ALL" },
];

/** Chip rows above the gallery. The tag row narrows the columns view
 *  client-side and drives the project-wide tag view's query — one filter,
 *  both surfaces. The user row is a single-select "generated by" narrowing,
 *  applied client-side on both surfaces (see Gallery.tsx and TagView.tsx). */
export function TagFilterBar() {
  const defs = useEffectiveTagDefs();
  const users = useDiscoveredUsers();
  const activeFilter = useTagsStore((s) => s.activeFilter);
  const filterMode = useTagsStore((s) => s.filterMode);
  const activeUserFilter = useTagsStore((s) => s.activeUserFilter);
  const toggleFilter = useTagsStore((s) => s.toggleFilter);
  const setFilterMode = useTagsStore((s) => s.setFilterMode);
  const setUserFilter = useTagsStore((s) => s.setUserFilter);
  const clearFilter = useTagsStore((s) => s.clearFilter);

  if (defs.length === 0 && users.length === 0) return null;
  const isOn = (name: string) => activeFilter.some((t) => tagsEqual(t, name));

  return (
    <div className="flex flex-col shrink-0 border-b border-border">
      {defs.length > 0 && (
        <div className="flex items-center gap-2 px-2 py-1 bg-surface overflow-x-auto thin-scroll">
          <Icon name="sell" size={14} className="text-dim shrink-0" />
          <div className="flex items-center gap-1 flex-wrap">
            {defs.map((d) => {
              const on = isOn(d.name);
              return (
                <button
                  key={d.name}
                  type="button"
                  onClick={() => toggleFilter(d.name)}
                  title={
                    on
                      ? `Stop filtering by "${d.name}"`
                      : `Filter by "${d.name}"`
                  }
                  className={`flex items-center gap-1 px-1.5 py-[1px] text-xs whitespace-nowrap border ${
                    on
                      ? "bg-accent text-bg border-accent"
                      : "bg-bg border-dim hover:bg-panel"
                  }`}
                >
                  <span
                    className="w-[6px] h-[6px] shrink-0"
                    style={{ background: d.color }}
                  />
                  {d.name}
                </button>
              );
            })}
          </div>
          {activeFilter.length > 1 && (
            <ToggleGroup
              value={filterMode}
              options={MODES}
              onChange={setFilterMode}
              className="shrink-0"
            />
          )}
          {activeFilter.length > 0 && (
            <button
              type="button"
              onClick={clearFilter}
              title="Clear tag filter"
              className="px-1.5 py-[1px] text-xs bg-bg hover:bg-panel shrink-0"
            >
              CLEAR
            </button>
          )}
        </div>
      )}
      {users.length > 0 && (
        <div className="flex items-center gap-2 px-2 py-1 bg-surface overflow-x-auto thin-scroll">
          <Icon name="person" size={14} className="text-dim shrink-0" />
          <div className="flex items-center gap-1 flex-wrap">
            {users.map((u) => {
              const on =
                activeUserFilter != null && tagsEqual(activeUserFilter, u);
              return (
                <button
                  key={u}
                  type="button"
                  onClick={() => setUserFilter(u)}
                  title={
                    on ? `Stop filtering by user "${u}"` : `Filter by user "${u}"`
                  }
                  className={`px-1.5 py-[1px] text-xs whitespace-nowrap border ${
                    on
                      ? "bg-accent text-bg border-accent"
                      : "bg-bg border-dim hover:bg-panel"
                  }`}
                >
                  {u}
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
